#if !defined(CONSTANTS)

#define INITIAL_SCREEN_WIDTH	800
#define INITIAL_SCREEN_HEIGHT	600

#define FRAMES_PER_SECOND 60

#define UP		1
#define DOWN	2
#define LEFT	4
#define RIGHT	8

#define WORLD_MAP_SIZE_X 5
#define WORLD_MAP_SIZE_Y 5

#define GRID_MAP_SIZE_X	30
#define GRID_MAP_SIZE_Y	30

#define PLAYER_WORLD_START_X 2
#define PLAYER_WORLD_START_Y 2

#define PLAYER_GRID_START_X 15
#define PLAYER_GRID_START_Y 26

#define ACTION_STATE_SEEKING	0
#define ACTION_STATE_AVOIDANT	1

#define PLAYER_SPEED 1

#define GRID_FLOOR  0
#define GRID_WALL   1
#define GRID_EXIT   2

#define NUM_MODELS	10
#define NUM_MATS	8

#define MODE_PLAY				0
#define MODE_FREE_CAMERA		1
#define MODE_LEVEL_EDIT			2
#define MODE_PLAY_FIRST_PERSON  3

#define MAX_BULLETS 25
#define MAX_ENEMIES 20
#define MAX_PARTICLE_EMITTERS 30

#define CONSTANTS
#endif // !CONSTANTS


